import { useRouter } from 'next/router';
import {useState, useEffect}from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import {fetchItemData} from '@/modules/Data.js'

export default function TodoID() {
    const [itemId, setItemId]=useState("");
    const [loading, setLoading]=useState(true);
    const [text, setText]=useState("");
    const [data, setData]=useState(null);
    const router = useRouter();
    useEffect(() => {
        setItemId(router.query.id);
    },[router.query]);
    //console.log(router.asPath.split("/")[2]);
    useEffect(() => {
        async function setUp(){
            if(itemId != null){
                const token = await getToken({template: "codehooks"});
                fetchItemData(itemId, authToken);
                setLoading(false);
            }
            fetchItemData();
        }
        setUp();
    },[itemId]);



    if(loading){
        return(<span>loading...</span>)
    }else{return(
<>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.header}>ITEM {itemId}</h1>
      <main className={styles.main}>
        <input className={styles.newtodoitem} value={text} onChange={(e=>setText(e.target.value))}>
        </input>
      </main>
    </>
    )
    }

}