import { useRouter } from 'next/router';
import {useState, useEffect}from 'react';
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import CategorySelector from '@/components/CategorySelector.js'
import {fetchItemData, updateCheckBox, fetchCategories, fetchDataCategory} from '@/modules/Data.js'
import { useAuth, SignIn, UserButton } from "@clerk/nextjs";
import Link from 'next/link'


export default function Categories() {    

    const [categories, setCategories] = useState([]);
    const { isLoaded, userId, sessionId, getToken } = useAuth();
    const [loading, setLoading]=useState(true);
    const [deletedCategory, setDeletedCategory] = useState(false);
    const [itemCatDelList, setItemCatDelList] = useState([]);
    const [catToDel, setCatToDel] = useState("");

    const router = useRouter();

    function RedirectToHome(){
      router.push('/');
    }

    function deleteCategory(category){
        console.log(category);
        setCatToDel(category);
        async function getItems(){
            if(userId){
              const token = await getToken({template: "codehooks"});
              fetchDataCategory(setItemCatDelList, category, userId, token);

            }
          }
          getItems();

    }

    useEffect(() => {
        async function alterItems(){
            if(userId){
              const token = await getToken({template: "codehooks"});
              itemCatDelList.map(item => {
                async function alterItem(){
                    let newPost = { ...item}
                    newPost.category = "";
                    newPost = await updateCheckBox(newPost, token);
                }
                alterItem();
              });

            }
          }
          alterItems();

          setDeletedCategory(true);
    }, [itemCatDelList, catToDel]);


    //set category list 
    useEffect(() => {
        async function loadCategories(){
        if(userId){
            const token = await getToken({template: "codehooks"});
            fetchCategories(setCategories, userId, token);
        }
        }
        loadCategories()
        setLoading(false);
        setDeletedCategory(false);
    }, [deletedCategory]);

    if(loading){
        if(!userId){
            return <>
                <RedirectToHome/>
            </>
        }
        return(<span>loading...</span>)
    }
    if(!loading){
        if(!userId){
            return <>
                <RedirectToHome/>
            </>
        }
        return(
            <>
        <Head>
            <title>Categories</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
        <div className="pure-g" id="menu">
                <div className="pure-u-3-4">
                    <h1 className={styles.header}>Categories</h1>
                </div>
                <div className="pure-u-1-4">
                    <div className={styles.userButton}>
                        <UserButton></UserButton>
                    </div>
                </div>
            </div>
            {categories.map(cat => {
                if(cat!="" && cat!="New Category"){
                    const redirLinkTodos = "/todos/"+cat
                    const redirLinkDone = "/done/"+cat
                    return (
                        <div key={cat} className={styles.todoitem}>
                            <div className="pure-g" id="menu">
                                <div className="pure-u-1-5">
                                    {cat}
                                </div>
                                <div className="pure-u-1-5">
                                <Link href={redirLinkTodos}><button className="pure-button">Todos</button></Link>
                                </div>
                                <div className="pure-u-2-5">
                                <Link href={redirLinkDone}>Done</Link>
                                </div>
                                <div className="pure-u-1-5">
                                <span className={styles.deleteButton}>
                                    <button className="pure-button" onClick={() => deleteCategory(cat)}>Delete</button>
                                </span>
                                </div>
                            </div>
                        </div>
                    )
                }
            })}
            
        </main>
        </>

        )
    }
}