import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {useEffect, useState} from 'react'
import 'purecss/build/pure.css';
import { useAuth, SignIn, UserButton } from "@clerk/nextjs";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { isLoaded, userId, sessionId, getToken } = useAuth();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.todoitem}>
          <h1 className={styles.header}>Welcome to your todo list</h1>
          {/* <button>Log In</button> */}
          {userId ? <UserButton></UserButton> : <SignIn></SignIn>}
        </div>
      </main>
    </>
  )
}
