import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {useEffect, useState, createElement} from 'react'
import CategorySelector from '@/components/CategorySelector.js'
import ToDoItem from '@/components/ToDoItem.js'
import { useAuth, SignIn, UserButton } from "@clerk/nextjs";
import {fetchDataUnchecked, postDataUnchecked, fetchCategories} from '@/modules/Data.js'
import {useRouter} from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const API_ENDPOINT = 'https://backend-9f6j.api.codehooks.io/dev/toDoItem'
  const API_KEY = '271f7152-88ba-4d48-bc2d-f433a2c6d37d'

  const [posts, setPosts] = useState([]);
  const [loading, setLoading]=useState(true);
  const [newName, setNewName]=useState("");
  const [newCategoryHidden, setNewCategoryHidden] = useState(true);
  const [newCategory, setNewCategory] = useState("");
  const [selectedCategory, setSelectedCategory] = useState("");
  const [newGet, setNewGet] = useState(false);
  const [categories, setCategories] = useState([]);
  const { isLoaded, userId, sessionId, getToken } = useAuth();
  const [newChecked, setNewChecked] = useState(false);

  let router = useRouter();

  function RedirectToHome(){
    router.push('/');
  }

  let listItems=posts.map( (post) => <ToDoItem key={post.date} post={post} newChecked={newChecked} setNewChecked={setNewChecked}/>);

  // get data from the database
  useEffect(() => {
    async function loadToDoData(){
      if(userId){
        const token = await getToken({template: "codehooks"});
        fetchDataUnchecked(setPosts, setLoading, userId, token);
      }
    }
    loadToDoData();
    setNewChecked(false);
  }, [newGet, isLoaded, newChecked]);

  // post data to the database
  async function postData(selectedCategory) {
    if(userId){
      const token = await getToken({template: "codehooks"});
      postDataUnchecked(token, newGet, setNewGet, userId, newName, selectedCategory);
    }
  }

  //set category list whenever a new post comes in
  useEffect(() => {
    async function loadCategories(){
      if(userId){
        const token = await getToken({template: "codehooks"});
        fetchCategories(setCategories, userId, token);
      }
    }
    loadCategories()
  }, [posts]);

  // if valid name, add to database
  function addName() {
    let index = document.getElementById("categoriesSelector").selectedIndex;
    let curCategory = categories[index];
    if(index == 1){
      curCategory = newCategory;
    }
    if(newName!=""){
      postData(curCategory);
    }
  }

  if(loading){
    if(!userId){
      return <>
          <RedirectToHome/>
      </>
  }
    return(<span>loading...</span>)
  }else{
    if(!userId){
      return <>
          <RedirectToHome/>
      </>
    }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pure-g" id="menu">
            <div className="pure-u-3-4">
                <h1 className={styles.header}>TODOS</h1>
            </div>
            <div className="pure-u-1-4">
                <div className={styles.userButton}>
                    <UserButton></UserButton>
                </div>
            </div>
        </div>
      <main className={styles.main}>
        <div className={styles.todoitem}>
          <p>New To Do Item: 
            <input className={styles.newtodoitem} value={newName} onChange={(e=>setNewName(e.target.value))}>
            </input> 
            <span className={styles.categoryLabel}>Category:</span>
            <CategorySelector loading={loading} categories={categories} selectedCategory={selectedCategory} setSelectedCategory={setSelectedCategory}/>
            <input id="newCategoryInput" maxLength="20" hidden={newCategoryHidden} className={styles.newtodoitem} value={newCategory} onChange={(e=>setNewCategory(e.target.value))}>
            </input> 
            <span className={styles.newtodosubmit}>
              <button className="pure-button" onClick={addName}>Add Item</button> 
            </span>
            
            </p>
          </div>
          <div className={styles.todoitem}>
            <div key="category" className="pure-u-1-5 categoryDisplayed"><div className={styles.headerLabelCategory}>Category</div></div>
            <div key="content" className="pure-u-1-5"><div className={styles.headerLabels}>Description</div></div>
            {posts.map( (post) => <ToDoItem key={post.date} post={post} setNewChecked={setNewChecked}/>)}
        </div>
      </main>
    </>
  )
  }
}
